import SwiftUI
import StoreKit
struct CreditsView: View {

    @EnvironmentObject var creditsService: CreditsService
    @EnvironmentObject var storeKitService: StoreKitService
    private let creditProducts: [CreditProduct] = [
        CreditProduct(
            id: "com.aipanelschedules.credits_1",
            credits: 1,
            title: "1 Credit",
            subtitle: "Unlocks 1 Excel file",
            priceText: "—"
        ),
        CreditProduct(
            id: "com.aipanelschedules.credits_3",
            credits: 3,
            title: "3 Credits",
            subtitle: "Unlocks 3 Excel files",
            priceText: "—"
        ),
        CreditProduct(
            id: "com.aipanelschedules.credits_10",
            credits: 10,
            title: "10 Credits",
            subtitle: "Unlocks 10 Excel files",
            priceText: "—"
        )
    ]
    @State private var showingPurchaseConfirm = false
    @State private var selectedProduct: CreditProduct?
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {

                // MARK: - Balance
                VStack(alignment: .leading, spacing: 8) {
                    Text("Credits Balance")
                        .font(.headline)

                    HStack(spacing: 8) {
                        Image(systemName: "creditcard.fill")
                        Text("\(creditsService.credits) Credits Available")
                            .font(.title2)
                            .bold()
                    }

                    Text("Each credit unlocks one Excel file")
                        .font(.subheadline)
                        .foregroundColor(.secondary)
                }
                .padding()
                .background(Color(.secondarySystemBackground))
                .cornerRadius(12)

                // MARK: - Purchase Options (PLACEHOLDERS)
               

                VStack(alignment: .leading, spacing: 16) {
                    Text("Buy Credits")
                        .font(.headline)

                    ForEach(storeKitService.pricedProducts) { product in
                        let priceText =
                            storeKitService.products
                                .first(where: { $0.id == product.id })?
                                .displayPrice ?? "—"

                        creditOption(
                            product: CreditProduct(
                                id: product.id,
                                credits: product.credits,
                                title: product.title,
                                subtitle: product.subtitle,
                                priceText: priceText
                            )
                        )
                    }
                }
                

                // MARK: - How It Works
                VStack(alignment: .leading, spacing: 8) {
                    Text("How credits work")
                        .font(.headline)

                    Text("""
• Scanning PDFs is free
• Credits unlock Excel files generated by scans
• You only spend a credit when you unlock an Excel
• Unlocked files remain available forever
• Credits sync across all your devices
""")
                    .font(.footnote)
                    .foregroundColor(.secondary)
                }
            }
            .padding()
        }
        .navigationTitle("Credits")
        .onAppear {
            creditsService.startListening()

            Task {
                await storeKitService.loadProducts()
            }
        }
        .confirmationDialog(
            "Simulate Purchase",
            isPresented: $showingPurchaseConfirm,
            titleVisibility: .visible
        ) {
            if let product = selectedProduct {
                Button("Add \(product.credits) Credit\(product.credits == 1 ? "" : "s")") {
                    print("🧪 DEV PURCHASE CONFIRMED:", product.id)
                    creditsService.grantCredits(product.credits)
                }
            }
            Button("Cancel", role: .cancel) { }
        } message: {
            if let product = selectedProduct {
                Text("This will add \(product.credits) credit\(product.credits == 1 ? "" : "s") to your account for testing.")
            }
        }
    }

    // MARK: - Credit Row
    private func creditOption(product: CreditProduct) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(product.title)
                .font(.headline)

            Text(product.subtitle)
                .font(.subheadline)
                .foregroundColor(.secondary)
            Button {
                Task {
                    guard let storeProduct = storeKitService.products.first(
                        where: { $0.id == product.id }
                    ) else {
                        print("❌ StoreKit product not found:", product.id)
                        return
                    }

                    let success = await storeKitService.purchase(storeProduct)

                    if success {
                        let credits = storeKitService.creditsForProductID(storeProduct.id)
                        creditsService.grantCredits(credits)
                    }
                }
            } label: {
                Text(product.priceText)
                    .frame(maxWidth: .infinity)
                    .padding()
            }
            .buttonStyle(.borderedProminent)
            .buttonStyle(.borderedProminent)
#if DEBUG
            .disabled(false)
#else
            .disabled(true)
#endif
        }
        .padding()
        .background(Color(.secondarySystemBackground))
        .cornerRadius(12)
    }
}
