import SwiftUI
import StoreKit

struct CreditsView: View {
    @EnvironmentObject var creditsService: CreditsService
    @EnvironmentObject var storeKitService: StoreKitService
    
    @State private var showingRestoreResult = false
    @State private var showingPurchaseConfirm = false
    @State private var selectedProduct: CreditProduct?
    
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {

                // MARK: - Balance
                VStack(alignment: .leading, spacing: 8) {
                    Text("Credits Balance")
                        .font(.headline)

                    HStack(spacing: 8) {
                        Image(systemName: "creditcard.fill")
                        Text("\(creditsService.credits) Credits Available")
                            .font(.title2)
                            .bold()
                    }

                    Text("Each credit unlocks one Excel file")
                        .font(.subheadline)
                        .foregroundColor(.secondary)
                }
                .padding()
                .background(Color(.secondarySystemBackground))
                .cornerRadius(12)

                // MARK: - Purchase Options
                VStack(alignment: .leading, spacing: 16) {
                    Text("Buy Credits")
                        .font(.headline)

                    // We use the pricedProducts from the service because they
                    // contain the updated priceText from Apple's servers.
                    ForEach(storeKitService.pricedProducts) { product in
                        creditOption(product: product)
                    }
                }
                
                // MARK: - How It Works
                VStack(alignment: .leading, spacing: 8) {
                    Text("How credits work")
                        .font(.headline)

                    Text("""
• Scanning PDFs is free
• Credits unlock Excel files generated by scans
• You only spend a credit when you unlock an Excel
• Unlocked files remain available forever
• Credits sync across all your devices
""")
                    .font(.footnote)
                    .foregroundColor(.secondary)
                }
            }
            .padding()
        }
        .navigationTitle("Credits")
        // This is your SINGLE SOURCE OF TRUTH for granting credits.
        .onChange(of: storeKitService.purchaseEvent?.id) { _, _ in
            guard let event = storeKitService.purchaseEvent else { return }

            let credits = storeKitService.creditsForProductID(event.productID)
            guard credits > 0 else { return }

            print("✅ Granting \(credits) credits for:", event.productID)
            creditsService.grantCredits(credits)
        }
        .onAppear {
            creditsService.startListening()

            Task {
                await storeKitService.loadProducts()
            }
        }
        .confirmationDialog(
            "Simulate Purchase",
            isPresented: $showingPurchaseConfirm,
            titleVisibility: .visible
        ) {
            if let product = selectedProduct {
                Button("Add \(product.credits) Credit\(product.credits == 1 ? "" : "s")") {
                    print("🧪 DEV PURCHASE CONFIRMED:", product.id)
                    creditsService.grantCredits(product.credits)
                }
            }
            Button("Cancel", role: .cancel) { }
        } message: {
            if let product = selectedProduct {
                Text("This will add \(product.credits) credit\(product.credits == 1 ? "" : "s") to your account for testing.")
            }
        }
    }

    // MARK: - Credit Row
    private func creditOption(product: CreditProduct) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(product.title)
                .font(.headline)

            Text(product.subtitle)
                .font(.subheadline)
                .foregroundColor(.secondary)
            
            Button {
                Task {
                    guard let storeProduct = storeKitService.products.first(
                        where: { $0.id == product.id }
                    ) else {
                        print("❌ StoreKit product not found:", product.id)
                        return
                    }

                    // We call purchase, but we DON'T grant credits here.
                    // The .onChange above will handle it when the purchase is verified.
                    _ = await storeKitService.purchase(storeProduct)
                }
            } label: {
                Text(product.priceText)
                    .frame(maxWidth: .infinity)
                    .padding()
            }
            .buttonStyle(.borderedProminent)
            // FIXED: The button is only disabled if the price hasn't loaded yet ("—").
            // This ensures TestFlight users can click it once the server responds.
            .disabled(product.priceText == "—")
        }
        .padding()
        .background(Color(.secondarySystemBackground))
        .cornerRadius(12)
    }
}
